service: cat-dog-lover-predictor

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  environment:
    MODEL_BUCKET: deploy-cat-dog-bucket
  iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "s3:GetObject"
        Resource:
          - "arn:aws:s3:::deploy-cat-dog-bucket/*"  

functions:
  predictor:
    handler: main.lambda_handler
    events:
      - http:
          path: predict
          method: post

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true  # Packages dependencies in an environment compatible with Lambda

package:
  individually: true

  exclude:
    - node_modules/**  # Exclude node modules (not needed for Python Lambda)
    - .git/**  # Exclude git history and configurations
    - .serverless/**  # Exclude Serverless build artifacts
    - aws/**  
    - model/training.py  # Exclude training script (only inference needed)
    - model/cat_dog_model.onnx  # Exclude ONNX model 
    - model/cat_dog_model.pkl  # Exclude the other model
    - __pycache__  # Exclude Python cache files
    - awscliv2.zip  # Exclude large AWS CLI installation file
    - "*.md"  # Exclude markdown files
    - "*.json"  # Exclude JSON files 
    - "*.txt"  # Exclude any text files not required for runtime
    - "README.md"  # Exclude README file
    - package-lock.json  # Exclude Node.js lock files
    - package.json  # Exclude Node.js package file


